#ifndef COLLATZ_COLLATZ_OPTIONS_H
#define COLLATZ_COLLATZ_OPTIONS_H


#define USE_SIMPLE_IMPLEMENTATION
//#define USE_FAST_IMPLEMENTATION
#define ENABLE_STATISTICS
//#define ENABLE_STEP_DEBUGGING


#endif //COLLATZ_COLLATZ_OPTIONS_H
